"""
Writer Agent: turns analysis into a polished HTML briefing.
If LLM generation fails, deterministic HTML fallback still includes all required sections.
"""
import html
import json
from datetime import datetime, timedelta, timezone
from typing import Any, Callable, Dict, List, Optional

from backend.agents.base_agent import BaseAgent


SYSTEM_PROMPT = """You are the Writer Agent of an AI Research Crew.

You receive analyzed research insights and must produce a polished HTML technical briefing.

IMPORTANT: Respond with ONLY the HTML code. Start directly with <!DOCTYPE html>.

The HTML briefing MUST include ALL of these sections:
1. A header with the topic title and generation date
2. An executive summary section
3. EXACTLY 5 insight sections (one for each key insight), each with:
   - A numbered title (e.g., "Insight 1: ...")
   - A detail paragraph (2-4 sentences)
   - An importance badge (high=red, medium=amber, low=green) based on 'priority'
4. A Competitive Landscape section containing an HTML table comparing players across dimensions.
5. A confidence score progress bar
6. A sources section listing all URLs
7. A footer: "Generated by AI Research Crew"

Style requirements (all inline CSS):
- Dark professional design
- Background: #0f172a, Cards: #1e293b, Primary: #7c3aed, Accent: #2563eb
- White text, rounded corners (12px), max-width: 800px centered
- Font: system-ui, -apple-system, sans-serif
- Importance badges: Critical=#ef4444, High=#ef4444, Medium=#f59e0b, Low=#22c55e
- Competitive Table: 100% width, border-collapse, th with #334155 background, padded cells (12px), text-align left, table border 1px solid #334155
- Confidence bar: gradient from #7c3aed to #2563eb

CRITICAL: You MUST render ALL 5 insights and the competitive landscape table.
"""


def _safe_confidence_pct(confidence) -> int:
    try:
        val = float(confidence)
    except (TypeError, ValueError):
        return 50
    if val <= 1.0:
        return max(0, min(100, int(val * 100)))
    if val <= 100:
        return max(0, min(100, int(val)))
    return min(100, max(0, int(val)))


class WriterAgent(BaseAgent):
    def __init__(self, emit: Optional[Callable] = None):
        super().__init__(
            name="Writer",
            role="Technical Briefing Author",
            color="#d97706",
            emit=emit,
        )

    def _get_system_prompt_for_intent(self, intent: str) -> str:
        sections_desc = ""
        if intent == "educational":
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Overview\n"
                "3. Key Concepts\n"
                "4. Advantages\n"
                "5. Disadvantages\n"
                "6. Examples\n"
                "7. Conclusion\n"
                "8. A confidence score progress bar\n"
                "9. A sources section listing all URLs\n"
                "10. A footer: \"Generated by AI Research Crew\""
            )
        elif intent == "comparison":
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Overview\n"
                "3. Feature comparison (with a comparison table comparing players across dimensions)\n"
                "4. Pros/Cons\n"
                "5. Recommendation / Verdict\n"
                "6. A confidence score progress bar\n"
                "7. A sources section listing all URLs\n"
                "8. A footer: \"Generated by AI Research Crew\""
            )
        elif intent == "latest_news":
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Executive Summary\n"
                "3. Timeline of developments\n"
                "4. Key Developments\n"
                "5. Industry Impact\n"
                "6. Future Outlook\n"
                "7. A confidence score progress bar\n"
                "8. A sources section listing all URLs\n"
                "9. A footer: \"Generated by AI Research Crew\""
            )
        elif intent == "research":
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Abstract\n"
                "3. Background\n"
                "4. Methodology\n"
                "5. Results (including comparisons or data tables)\n"
                "6. Limitations\n"
                "7. A confidence score progress bar\n"
                "8. References / sources listing all URLs\n"
                "9. A footer: \"Generated by AI Research Crew\""
            )
        elif intent == "tutorial":
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Overview\n"
                "3. Prerequisites\n"
                "4. Step-by-Step Guide\n"
                "5. Practical Examples\n"
                "6. Common Pitfalls\n"
                "7. A confidence score progress bar\n"
                "8. A sources section listing all URLs\n"
                "9. A footer: \"Generated by AI Research Crew\""
            )
        elif intent == "troubleshooting":
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Problem Description\n"
                "3. Diagnostic Steps\n"
                "4. Solutions / Resolutions\n"
                "5. Preventive Actions\n"
                "6. A confidence score progress bar\n"
                "7. A sources section listing all URLs\n"
                "8. A footer: \"Generated by AI Research Crew\""
            )
        elif intent == "recommendation":
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Executive Summary\n"
                "3. Recommendation Overview\n"
                "4. Options Comparison\n"
                "5. Target Audience\n"
                "6. Verdict\n"
                "7. A confidence score progress bar\n"
                "8. A sources section listing all URLs\n"
                "9. A footer: \"Generated by AI Research Crew\""
            )
        elif intent == "historical":
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Timeline Overview\n"
                "3. Key Milestones\n"
                "4. Impact Analysis\n"
                "5. Evolution\n"
                "6. Conclusion\n"
                "7. A confidence score progress bar\n"
                "8. A sources section listing all URLs\n"
                "9. A footer: \"Generated by AI Research Crew\""
            )
        elif intent == "opinion":
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Executive Summary\n"
                "3. Core Debate\n"
                "4. Supporting Perspectives\n"
                "5. Opposing Perspectives\n"
                "6. Balanced Verdict\n"
                "7. A confidence score progress bar\n"
                "8. A sources section listing all URLs\n"
                "9. A footer: \"Generated by AI Research Crew\""
            )
        else:
            sections_desc = (
                "1. A header with the topic title and generation date\n"
                "2. Executive Summary\n"
                "3. Key Insights (at least 5 distinct points)\n"
                "4. A confidence score progress bar\n"
                "5. A sources section listing all URLs\n"
                "6. A footer: \"Generated by AI Research Crew\""
            )

        return f"""You are the Writer Agent of an AI Research Crew.

You receive analyzed research insights and must produce a polished HTML technical briefing.

IMPORTANT: Respond with ONLY the HTML code. Start directly with <!DOCTYPE html>.

The HTML briefing MUST include ALL of these sections in this order:
{sections_desc}

Style requirements (all inline CSS):
- Dark professional design
- Background: #0f172a, Cards: #1e293b, Primary: #7c3aed, Accent: #2563eb
- White text, rounded corners (12px), max-width: 800px centered
- Font: system-ui, -apple-system, sans-serif
- Importance badges (if any are used): Critical=#ef4444, High=#ef4444, Medium=#f59e0b, Low=#22c55e
- Competitive Table (if any comparisons or data tables are used): 100% width, border-collapse, th with #334155 background, padded cells (12px), text-align left, table border 1px solid #334155
- Confidence bar: gradient from #7c3aed to #2563eb
"""

    def run(self, input_data: Any) -> dict:
        self.emit_status("working")

        topic = input_data.get("topic", "Research Topic")
        intent = input_data.get("intent", "educational")
        search_strategy = input_data.get("search_strategy", "knowledge")
        summary = input_data.get("executiveSummary", "No summary available.")
        insights = self._normalize_insights(input_data.get("insights", []))
        confidence = input_data.get("confidenceScore", 50)
        competitive = input_data.get("competitiveLandscape", {})
        raw_results = input_data.get("raw_results", [])
        raw_news = input_data.get("raw_news", [])

        self.emit_log(f"Drafting technical briefing for: '{topic}'")
        self.emit_log(f"Working with {len(insights)} insights, {len(raw_results)} sources")

        sources = self._build_sources(raw_results, raw_news)
        conf_pct = _safe_confidence_pct(confidence)

        user_prompt = (
            f"Topic: {topic}\n"
            f"Intent: {intent}\n"
            f"Date: {datetime.now(timezone(timedelta(hours=5, minutes=30))).strftime('%B %d, %Y')}\n\n"
            f"Executive Summary/Abstract: {summary}\n\n"
            f"Key Insights (YOU MUST INCLUDE ALL {len(insights)} OF THESE):\n{json.dumps(insights, indent=2)}\n\n"
            f"Competitive/Option Landscape:\n{json.dumps(competitive, indent=2)}\n\n"
            f"Confidence Score: {conf_pct}%\n\n"
            f"Sources:\n{json.dumps(sources, indent=2)}\n\n"
            f"Generate complete HTML now. Include all sections and all insights."
        )

        try:
            self.emit_log("Generating HTML document...")
            system_prompt = self._get_system_prompt_for_intent(intent)
            html_doc = self.call_llm(system_prompt, user_prompt, max_tokens=6000)

            html_doc = html_doc.strip()
            if html_doc.startswith("```"):
                lines = html_doc.split("\n")
                html_doc = "\n".join(lines[1:])
                if html_doc.rstrip().endswith("```"):
                    html_doc = html_doc.rstrip()[:-3]

            if not self._looks_like_valid_html(html_doc, intent):
                self.emit_log("Writer output missing required HTML sections, using fallback renderer")
                html_doc = self._wrap_fallback_html(topic, summary, insights, confidence, sources, competitive, intent)

            word_count = len(html_doc.split())
            self.emit_log(f"Briefing drafted: {word_count} words")

            self.emit_status("done")
            return {
                "topic": topic,
                "intent": intent,
                "search_strategy": search_strategy,
                "html": html_doc,
                "word_count": word_count,
            }

        except Exception as exc:
            self.emit_log(f"Writer failed: {str(exc)[:120]} -- rendering deterministic HTML")
            html_doc = self._wrap_fallback_html(topic, summary, insights, confidence, sources, competitive, intent)
            self.emit_status("done")
            return {
                "topic": topic,
                "intent": intent,
                "search_strategy": search_strategy,
                "html": html_doc,
                "word_count": len(html_doc.split()),
            }

    def _looks_like_valid_html(self, html_doc: str, intent: str) -> bool:
        h = (html_doc or "").lower()
        return all(
            token in h
            for token in ["<html", "sources"]
        )

    def _normalize_insights(self, insights: Any) -> List[Dict[str, str]]:
        normalized: List[Dict[str, str]] = []
        if not isinstance(insights, list):
            insights = []

        for item in insights:
            if not isinstance(item, dict):
                continue
            normalized.append(
                {
                    "headline": str(item.get("headline", "Untitled insight")).strip() or "Untitled insight",
                    "body": str(item.get("body", "Details unavailable.")).strip() or "Details unavailable.",
                    "priority": str(item.get("priority", "Medium")).strip().title() or "Medium",
                    "source": str(item.get("source", "Unknown")).strip() or "Unknown",
                }
            )

        while len(normalized) < 5:
            normalized.append(
                {
                    "headline": "Additional evidence signal",
                    "body": "More details are available in source references.",
                    "priority": "Medium",
                    "source": "Unknown",
                }
            )

        return normalized[:5]

    def _build_sources(self, raw_results: List[Dict], raw_news: List[Dict]) -> List[Dict[str, str]]:
        rows: List[Dict[str, str]] = []
        seen = set()

        for r in raw_results[:15]:
            url = str(r.get("source") or r.get("url") or "").strip()
            if not url or url in seen:
                continue
            seen.add(url)
            rows.append(
                {
                    "type": "web",
                    "title": str(r.get("title", "Untitled")).strip() or "Untitled",
                    "url": url,
                    "domain": str(r.get("domain", "")).strip(),
                    "date": str(r.get("date", "")).strip(),
                }
            )

        for n in raw_news[:8]:
            url = str(n.get("url") or n.get("source") or "").strip()
            if not url or url in seen:
                continue
            seen.add(url)
            rows.append(
                {
                    "type": "news",
                    "title": str(n.get("title", "Untitled")).strip() or "Untitled",
                    "url": url,
                    "domain": str(n.get("domain", "")).strip(),
                    "date": str(n.get("date", "")).strip(),
                }
            )

        return rows[:12]

    def _build_competitive_table_html(self, competitive: Dict) -> str:
        dimensions = competitive.get("dimensions", ["Performance", "Cost", "Maturity", "Ecosystem"])
        players = competitive.get("players", ["Unknown", "Unknown", "Unknown"])
        data = competitive.get("data", [["-", "-", "-", "-"]] * 3)

        if not isinstance(dimensions, list) or not dimensions:
            dimensions = ["Performance", "Cost", "Maturity", "Ecosystem"]
        if not isinstance(players, list) or not players:
            players = ["Unknown", "Unknown", "Unknown"]
        if not isinstance(data, list) or not data:
            data = [["-", "-", "-", "-"]] * 3

        dimensions = [str(d) for d in dimensions[:4]]
        while len(dimensions) < 4:
            dimensions.append(f"Metric {len(dimensions)+1}")

        players = [str(p) for p in players[:3]]
        while len(players) < 3:
            players.append("Unknown")

        rows_html = ""
        for idx, player in enumerate(players):
            row = data[idx] if idx < len(data) and isinstance(data[idx], list) else []
            row_vals = [str(v) for v in row[:4]]
            while len(row_vals) < 4:
                row_vals.append("-")
            cells = "".join(
                f"<td style='padding:12px;border:1px solid #334155;color:#e2e8f0'>{html.escape(v)}</td>"
                for v in row_vals
            )
            rows_html += (
                f"<tr><td style='padding:12px;border:1px solid #334155;color:#f8fafc;font-weight:600'>{html.escape(player)}</td>"
                f"{cells}</tr>"
            )

        header_dims = "".join(
            f"<th style='padding:12px;border:1px solid #334155;background:#334155;color:#e2e8f0;text-align:left'>{html.escape(d)}</th>"
            for d in dimensions
        )

        return (
            "<table style='width:100%;border-collapse:collapse;border:1px solid #334155'>"
            "<thead><tr>"
            "<th style='padding:12px;border:1px solid #334155;background:#334155;color:#e2e8f0;text-align:left'>Player</th>"
            f"{header_dims}</tr></thead><tbody>{rows_html}</tbody></table>"
        )

    def _wrap_fallback_html(
        self,
        topic: str,
        summary: str,
        insights: List[Dict[str, str]],
        confidence,
        sources: List[Dict[str, str]],
        competitive: Dict,
        intent: str = "educational",
    ) -> str:
        ist = timezone(timedelta(hours=5, minutes=30))
        date_str = datetime.now(ist).strftime("%B %d, %Y")
        conf_pct = _safe_confidence_pct(confidence)

        # Distribute insights into headers based on intent
        if intent == "educational":
            headers = ["Overview", "Key Concepts", "Advantages", "Disadvantages", "Examples", "Conclusion"]
        elif intent == "comparison":
            headers = ["Overview", "Feature Comparison", "Pros & Cons", "Recommendation"]
        elif intent == "latest_news":
            headers = ["Executive Summary", "Timeline", "Key Developments", "Industry Impact", "Future Outlook"]
        elif intent == "research":
            headers = ["Abstract", "Background", "Methodology", "Results", "Limitations", "References"]
        elif intent == "tutorial":
            headers = ["Overview", "Prerequisites", "Step-by-Step Guide", "Examples", "Common Pitfalls"]
        elif intent == "troubleshooting":
            headers = ["Problem Description", "Diagnostic Steps", "Solutions", "Preventive Actions", "Resources"]
        elif intent == "recommendation":
            headers = ["Executive Summary", "Recommendation Overview", "Options Comparison", "Target Audience", "Verdict"]
        elif intent == "historical":
            headers = ["Timeline Overview", "Key Milestones", "Impact Analysis", "Evolution", "Conclusion"]
        elif intent == "opinion":
            headers = ["Executive Summary", "Core Debate", "Supporting Perspectives", "Opposing Perspectives", "Balanced Verdict"]
        else:
            headers = ["Executive Summary", "Key Insights", "Outlook"]

        sections_html = ""
        for idx, header in enumerate(headers):
            if idx < len(insights):
                ins = insights[idx]
                title = ins.get("headline", f"Details on {header}")
                detail = ins.get("body", "No details available.")
                priority = ins.get("priority", "Medium").lower()
                source = ins.get("source", "Unknown")
            else:
                title = f"{header} Analysis"
                detail = f"Further discussion regarding {header.lower()} is provided in the references."
                priority = "medium"
                source = "Evidence synthesis"

            badge_color = {
                "high": "#ef4444",
                "critical": "#ef4444",
                "medium": "#f59e0b",
                "low": "#22c55e",
            }.get(priority, "#f59e0b")

            sections_html += (
                f"<div style='background:#1e293b;padding:20px;border-radius:12px;margin-bottom:16px;border-left:4px solid {badge_color}'>"
                "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px'>"
                f"<h3 style='margin:0;color:#f8fafc'>{html.escape(header)}: {html.escape(title)}</h3>"
                f"<span style='background:{badge_color};color:#fff;padding:2px 10px;border-radius:20px;font-size:12px;text-transform:uppercase'>{html.escape(priority)}</span>"
                "</div>"
                f"<p style='color:#94a3b8;margin:0;line-height:1.6'>{detail}</p>"
                f"<p style='color:#64748b;margin:8px 0 0 0;font-size:12px'>Source: {html.escape(source)}</p>"
                "</div>"
            )

        source_items = ""
        for src in sources[:12]:
            title_text = html.escape(src.get("title", "Untitled"))
            url = html.escape(src.get("url", ""))
            src_type = html.escape(src.get("type", "web").upper())
            source_items += (
                "<li style='color:#94a3b8;margin-bottom:8px'>"
                f"[{src_type}] {title_text}: "
                f"<a href='{url}' target='_blank' style='color:#93c5fd;text-decoration:none'>{url}</a>"
                "</li>"
            )

        if not source_items:
            source_items = "<li style='color:#94a3b8'>No sources available.</li>"

        # Show table/competitive details if relevant
        show_table = intent in ["comparison", "recommendation", "research"] or (competitive and competitive.get("players") and any(p != "Unknown" for p in competitive.get("players", [])))
        competitive_html = ""
        if show_table:
            competitive_table = self._build_competitive_table_html(competitive or {})
            competitive_html = f"""
<div style="background:#1e293b;padding:24px;border-radius:12px;margin-top:24px">
<h2 style="color:#c4b5fd;margin-top:0">Competitive Landscape / Options</h2>
{competitive_table}
</div>"""

        return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(topic)} - AI Research Briefing</title></head>
<body style="margin:0;padding:40px 20px;background:#0f172a;color:#f8fafc;font-family:system-ui,-apple-system,sans-serif">
<div style="max-width:800px;margin:0 auto">
<div style="text-align:center;margin-bottom:40px">
<h1 style="font-size:28px;margin-bottom:8px;background:linear-gradient(135deg,#7c3aed,#2563eb);-webkit-background-clip:text;-webkit-text-fill-color:transparent">{html.escape(topic)}</h1>
<p style="color:#64748b">AI Research Briefing ({html.escape(intent.replace('_', ' ').title())}) - {date_str}</p>
</div>
<div style="background:#1e293b;padding:24px;border-radius:12px;margin-bottom:24px;border-left:4px solid #7c3aed">
<h2 style="color:#c4b5fd;margin-top:0">Executive Summary</h2>
<p style="color:#cbd5e1;line-height:1.7">{html.escape(summary)}</p>
<div style="margin-top:12px;display:flex;align-items:center;gap:8px">
<span style="color:#64748b">Confidence:</span>
<div style="flex:1;background:#334155;border-radius:10px;height:8px;overflow:hidden"><div style="width:{conf_pct}%;height:100%;background:linear-gradient(90deg,#7c3aed,#2563eb);border-radius:10px"></div></div>
<span style="color:#7c3aed;font-weight:bold">{conf_pct}%</span>
</div></div>
<h2 style="color:#c4b5fd;margin-bottom:16px">Structured Briefing Sections</h2>
{sections_html}
{competitive_html}
<div style="background:#1e293b;padding:24px;border-radius:12px;margin-top:24px">
<h2 style="color:#c4b5fd;margin-top:0">Sources</h2>
<ul style="padding-left:20px">{source_items}</ul>
</div>
<p style="text-align:center;color:#475569;margin-top:32px;font-size:13px">Generated by AI Research Crew - Multi-Agent Agentic Workflow</p>
</div></body></html>"""
